import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Omnibite",
  description: "Generated by Omnibite",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="navbar">
          <div className="navbar-content">
            <h1 className="logo"> the Neighborhood</h1>
            <div className="nav-links">
              <Link href="/" className="nav-link">
                Home
              </Link>
              <Link href="/feedback" className="nav-link">
                Feedback
              </Link>
              <Link href="/help" className="nav-link">
                Help
              </Link>
            </div>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}